AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: EventsTable
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  EventsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'POST,GET,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  CreateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/create-event/
      Handler: index.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          EVENTS_TABLE: !Ref EventsTable
      # 👇 ADD THIS POLICIES SECTION
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApi
            Path: /events
            Method: POST

Outputs:
  ApiGatewayUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${EventsApi}.execute-api.${AWS::Region}.amazonaws.com/prod/events"